name: demo work flow

on:
  push:

jobs:
  demo-job:
    runs-on: ubuntu-latest
    steps:
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ tojson(github) }}
        run: echo "$GITHUB_CONTEX"
      - name: github job context
        env:
          JOB_CONTEXT: ${{ tojson(job) }}
        run: echo "$JOB_CONTEXT"